# =============================================================================
# Digital Finance Tracker - Alert Model
# PURPOSE: Alert database model for financial anomaly alerts
# =============================================================================
"""
Alert Model Module (Foundation)

This module defines the Alert model for the local database:
- Stores financial anomaly alerts
- Supports 5 alert types (high spending, large transaction, etc.)
- Foundation for anomaly detection feature

Database Table: alerts
Primary Key: id (UUID)
Foreign Key: user_id (references users.id)
Foreign Key: transaction_id (optional, references transactions.id)
Foreign Key: category_id (optional, references categories.id)

AI Foundation:
    Created as foundation for anomaly detection feature.
    The model is ready; detection logic will be added with AI integration.
    Alerts can be created manually or by future AI anomaly detection.

ALERT TYPES:
    - HIGH_SPENDING: Spending in category exceeds baseline
    - LARGE_TRANSACTION: Single transaction exceeds threshold
    - UNUSUAL_CATEGORY: Unusual spending pattern for user
    - BUDGET_WARNING: Approaching budget limit
    - BUDGET_EXCEEDED: Budget exceeded

SEVERITY LEVELS:
    - LOW: Informational, minor anomaly
    - MEDIUM: Notable, should review
    - HIGH: Significant, requires attention
    - CRITICAL: Urgent, potential issue

Relationship:
    - Many Alerts belong to one User (N:1)
    - Alert may reference a Transaction (optional)
    - Alert may reference a Category (optional)

Usage:
    from app.models import Alert, AlertType, AlertSeverity

    # Create alert
    alert = Alert(
        user_id=user.id,
        alert_type=AlertType.LARGE_TRANSACTION,
        severity=AlertSeverity.MEDIUM,
        title="Large Transaction Detected",
        message="$500.00 spent at Amazon exceeds your typical spending",
        transaction_id=transaction.id,
    )
    db.session.add(alert)
    db.session.commit()

    # Get undismissed alerts for user
    active_alerts = Alert.query.filter_by(
        user_id=user.id,
        is_dismissed=False
    ).order_by(Alert.created_at.desc()).all()

Notes:
    - is_dismissed defaults to False
    - data field stores extra context (baseline, threshold, etc.)
    - Use Alert.dismiss() method to mark as dismissed
"""

import uuid
from datetime import datetime, timezone
from typing import Optional, Dict, Any, TYPE_CHECKING

from sqlalchemy import String, Boolean, DateTime, Text, not_
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.extensions import db
from app.models.enums import AlertType, AlertSeverity

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.transaction import Transaction
    from app.models.category import Category


# =============================================================================
# ALERT MODEL
# =============================================================================


class Alert(db.Model):
    """
    Alert model representing a financial anomaly alert.

    This model stores alerts generated by the anomaly detection system
    (or created manually). Users can dismiss alerts they've reviewed.

    Attributes:
        id: Primary key UUID
        user_id: Foreign key to User
        alert_type: Type of alert (AlertType enum)
        severity: Alert severity (AlertSeverity enum)
        title: Short alert title
        message: Detailed alert message
        is_dismissed: Whether user has dismissed this alert
        dismissed_at: When alert was dismissed
        transaction_id: Optional FK to triggering transaction
        category_id: Optional FK to related category
        data: JSON metadata (baseline, threshold, etc.)
        created_at: When alert was created

    Relationships:
        user: Many-to-One with User
        transaction: Optional Many-to-One with Transaction
        category: Optional Many-to-One with Category

    Example:
        >>> alert = Alert.query.filter_by(user_id=user.id, is_dismissed=False).first()
        >>> print(f"{alert.severity.value}: {alert.title}")
        >>> alert.dismiss()  # Mark as dismissed
    """

    __tablename__ = "alerts"

    # =========================================================================
    # PRIMARY KEY
    # =========================================================================

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc="Primary key UUID",
    )

    # =========================================================================
    # FOREIGN KEYS
    # =========================================================================

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        db.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="User who owns this alert",
    )

    transaction_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        db.ForeignKey("transactions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="Optional: Transaction that triggered this alert",
    )

    category_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        db.ForeignKey("categories.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="Optional: Category related to this alert",
    )

    # =========================================================================
    # ALERT FIELDS
    # =========================================================================

    alert_type: Mapped[AlertType] = mapped_column(
        db.Enum(
            AlertType,
            native_enum=False,
            length=50,
            values_callable=lambda obj: [e.value for e in obj],
            validate_strings=True,
        ),
        nullable=False,
        index=True,
        doc="Type of alert",
    )

    severity: Mapped[AlertSeverity] = mapped_column(
        db.Enum(
            AlertSeverity,
            native_enum=False,
            length=20,
            values_callable=lambda obj: [e.value for e in obj],
            validate_strings=True,
        ),
        nullable=False,
        default=AlertSeverity.MEDIUM,
        index=True,
        doc="Alert severity level",
    )

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Short alert title",
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="Detailed alert message",
    )

    # =========================================================================
    # STATUS FIELDS
    # =========================================================================

    is_dismissed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        index=True,
        doc="Whether user has dismissed this alert",
    )

    dismissed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="When alert was dismissed",
    )

    # =========================================================================
    # METADATA
    # =========================================================================

    data: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
        default=lambda: {},
        doc="Additional data (baseline, threshold, amount, etc.)",
    )

    # =========================================================================
    # TIMESTAMPS
    # =========================================================================

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
        doc="When alert was created",
    )

    # =========================================================================
    # RELATIONSHIPS
    # =========================================================================

    user: Mapped["User"] = relationship(
        "User",
        back_populates="alerts",
        doc="User who owns this alert",
    )

    transaction_rel: Mapped[Optional["Transaction"]] = relationship(
        "Transaction",
        foreign_keys=[transaction_id],
        doc="Transaction that triggered this alert (optional)",
    )

    category_rel: Mapped[Optional["Category"]] = relationship(
        "Category",
        foreign_keys=[category_id],
        doc="Category related to this alert (optional)",
    )

    # =========================================================================
    # INSTANCE METHODS
    # =========================================================================

    def dismiss(self) -> None:
        """
        Mark this alert as dismissed.

        Sets is_dismissed=True and records the dismissal timestamp.
        Note: Caller is responsible for committing the session.

        Example:
            >>> alert.dismiss()
            >>> db.session.commit()
        """
        self.is_dismissed = True
        self.dismissed_at = datetime.now(timezone.utc)

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert alert to dictionary for API responses.

        Returns:
            Dictionary representation of the alert

        Example:
            >>> alert.to_dict()
            {
                "id": "uuid-string",
                "alert_type": "high_spending",
                "severity": "medium",
                "title": "High Spending Alert",
                ...
            }
        """
        return {
            "id": str(self.id),
            "user_id": str(self.user_id),
            "alert_type": self.alert_type.value,
            "severity": self.severity.value,
            "title": self.title,
            "message": self.message,
            "is_dismissed": self.is_dismissed,
            "dismissed_at": (
                self.dismissed_at.isoformat() if self.dismissed_at else None
            ),
            "transaction_id": str(self.transaction_id) if self.transaction_id else None,
            "category_id": str(self.category_id) if self.category_id else None,
            "data": self.data or {},
            "created_at": self.created_at.isoformat(),
        }

    # =========================================================================
    # CLASS METHODS
    # =========================================================================

    @classmethod
    def get_active_count(cls, user_id: uuid.UUID) -> int:
        """
        Get count of active (undismissed) alerts for a user.

        Args:
            user_id: User's UUID

        Returns:
            Number of active alerts

        Example:
            >>> active_count = Alert.get_active_count(user.id)
            >>> print(f"You have {active_count} active alerts")
        """
        return cls.query.filter(
            cls.user_id == user_id,
            not_(cls.is_dismissed),
        ).count()

    @classmethod
    def dismiss_all(cls, user_id: uuid.UUID) -> int:
        """
        Dismiss all alerts for a user.

        Args:
            user_id: User's UUID

        Returns:
            Number of alerts dismissed

        Example:
            >>> count = Alert.dismiss_all(user.id)
            >>> print(f"Dismissed {count} alerts")
        """
        now = datetime.now(timezone.utc)
        result = cls.query.filter(
            cls.user_id == user_id,
            not_(cls.is_dismissed),
        ).update(
            {
                "is_dismissed": True,
                "dismissed_at": now,
            }
        )
        db.session.commit()
        return result

    # =========================================================================
    # STRING REPRESENTATION
    # =========================================================================

    def __repr__(self) -> str:
        return (
            f"<Alert(id={self.id}, type={self.alert_type.value}, "
            f"severity={self.severity.value}, dismissed={self.is_dismissed})>"
        )


# =============================================================================
# MODULE EXPORTS
# =============================================================================

__all__ = [
    "Alert",
]
