"""add email_verified

Revision ID: 0288d252f0a7
Revises: b2c3d4e5
Create Date: 2026-01-19 23:07:25.317404

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0288d252f0a7"
down_revision = "b2c3d4e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.alter_column(
            "alert_type",
            existing_type=sa.VARCHAR(length=17),
            type_=sa.Enum(
                "high_spending",
                "large_transaction",
                "unusual_category",
                "budget_warning",
                "budget_exceeded",
                name="alerttype",
                native_enum=False,
                length=50,
            ),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "severity",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="alertseverity",
                native_enum=False,
                length=20,
            ),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("idx_alert_user_dismissed"))
        batch_op.create_index(
            batch_op.f("ix_alerts_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_transaction_id"), ["transaction_id"], unique=False
        )

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "idx_notification_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "idx_notification_user_type", ["user_id", "notification_type"], unique=False
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_transaction_user_ai_source", ["user_id", "ai_source"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email_verified",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "account_status",
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                "pending",
                "active",
                "suspended",
                "deactivated",
                name="account_status_enum",
                native_enum=False,
            ),
            existing_nullable=False,
        )
        batch_op.drop_column("picture")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("picture", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("email_verified")
        batch_op.alter_column(
            "account_status",
            existing_type=sa.Enum(
                "pending",
                "active",
                "suspended",
                "deactivated",
                name="account_status_enum",
                native_enum=False,
            ),
            type_=sa.VARCHAR(length=12),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("idx_transaction_user_ai_source")

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("idx_notification_user_type")
        batch_op.drop_index("idx_notification_user_created")

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_category_id"))
        batch_op.create_index(
            batch_op.f("idx_alert_user_dismissed"),
            ["user_id", "is_dismissed"],
            unique=False,
        )
        batch_op.alter_column(
            "severity",
            existing_type=sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="alertseverity",
                native_enum=False,
                length=20,
            ),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "alert_type",
            existing_type=sa.Enum(
                "high_spending",
                "large_transaction",
                "unusual_category",
                "budget_warning",
                "budget_exceeded",
                name="alerttype",
                native_enum=False,
                length=50,
            ),
            type_=sa.VARCHAR(length=17),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
