"""Create users and transactions tables with ERD constraints

Revision ID: 0ef6d8b45cc5
Revises:
Create Date: 2025-12-19 21:10:45.730328

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0ef6d8b45cc5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("auth0_id", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("picture", sa.Text(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "account_status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "SUSPENDED",
                name="account_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", name="user_role_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("salary_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_account_status"), ["account_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_users_auth0_id"), ["auth0_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "INCOME", "EXPENSE", name="transaction_type_enum", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("date", sa.String(length=50), nullable=False),
        sa.Column("merchant_name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_transaction_user_category", ["user_id", "category"], unique=False
        )
        batch_op.create_index(
            "idx_transaction_user_date", ["user_id", "date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_transaction_type"),
            ["transaction_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_user_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_transaction_type"))
        batch_op.drop_index(batch_op.f("ix_transactions_date"))
        batch_op.drop_index(batch_op.f("ix_transactions_category"))
        batch_op.drop_index("idx_transaction_user_date")
        batch_op.drop_index("idx_transaction_user_category")

    op.drop_table("transactions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_auth0_id"))
        batch_op.drop_index(batch_op.f("ix_users_account_status"))

    op.drop_table("users")
    # ### end Alembic commands ###
